//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the build system.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: AssemblyTitle("Crowbar")]
[assembly: AssemblyDescription("Crowbar is an application testing library for ASP.NET MVC 3 and 4.")]
[assembly: AssemblyProduct("Crowbar")]
[assembly: AssemblyCopyright("Copyright (c) Mattias Rydengren 2013")]
[assembly: AssemblyVersion("0.9.5")]
[assembly: AssemblyInformationalVersion("0.9.5")]
[assembly: AssemblyFileVersion("0.9.5")]
[assembly: AssemblyDelaySign(false)]
